config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  delete '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  namespace :admin do
    get '/dashboard', to: 'base#dashboard'
    resources :categories
    resources :images
    resources :users
    resources :ideas, only: [:index, :create, :show, :delete]
  end
  resources :users do
    resources :ideas
  end
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates_presence_of :user_id, :category_id, :title, :description, presence: true
  belongs_to :user
  belongs_to :category
  has_many :idea_images
  has_many :images, through: :idea_images
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_user

  def set_user
    @user = current_user
  end

  def index
    @ideas = current_user.ideas.all
  end

  def new
    @idea = current_user.ideas.new
    @categories = Category.all
    @images = Image.all
  end

  def create
    @idea = current_user.ideas.create(idea_params)
    if @idea.save
      params[:idea][:image_id].each do |image_id|
        unless image_id.empty?
          IdeaImage.create(idea: @idea, image_id: image_id)
        end
      end
      flash[:success] = "You have created, #{@idea.title}!"
      redirect_to user_idea_path(@user, @idea)
    else
      flash[:failed] = 'You forgot something'
      render :new
    end
  end

  def show
    @idea = Idea.find(params[:id])
    @images = @idea.images
  end

  def edit
    @idea = Idea.find(params[:id])
    @categories = Category.all
    @images = Image.all
  end

  def update
    @idea = Idea.find(params[:id])
    @idea.update(idea_params)
    if @idea.save
      flash[:success] = "#{@idea.title} updated!"
      redirect_to user_idea_path(@user, @idea)
    else
      flash[:failes] = "#{@idea.title} missing needed info"
      render :edit
    end
  end

  def destroy
    idea = Idea.find(params[:id])
    idea.destroy
    flash[:success] = "#{idea.title} was successfully deleted!"
    redirect_to user_ideas_path(@user)
  end

  private

  def idea_params
    params.require(:idea).permit(:category_id, :title, :description, :image_id)
  end
end

app/views/ideas/_form.html.erb
<%= form_for [@user, @idea] do |f| %>
  <%= f.label :category %>
  <%= f.collection_select(:category_id, @categories, :id, :name) %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.label :images %>
  <%= f.collection_select(:image_id, @images, :id, :title, {}, {multiple: true, size: @images.length}) %>
  <%= f.submit 'Save Idea' %>
<% end %>

app/views/ideas/index.html.erb
<h2><%= button_to 'Create Idea', new_user_idea_path(@user), method: 'get' %></h2>
<div class='ideas-index'>
  <% @ideas.each do |i| %>
    <h2><%= link_to i.title, user_idea_path(current_user, i) %></h2>
    <%= i.category.name %>
  <% end %>
</div>

app/views/ideas/new.html.erb
<%= form_for [@user, @idea] do |f| %>
  <%= f.label :category %>
  <%= f.collection_select(:category_id, Category.all, :id, :name) %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.submit 'Create Idea' %>
  <% end %>

app/views/ideas/show.html.erb
<h1><%= @idea.title %></h1>
<p>Description: <%= @idea.description %></p>
<p>Category: <%= @idea.category.name %></p>
<p>Images:</p>
<% @images.each do |i| %>
  <p><%= i.title %>
    <img src="<%= i.link %>"></p>
<% end %>
<%= button_to 'Edit', edit_user_idea_path(@user, @idea), method: 'get' %>
<%= button_to 'Delete', user_idea_path(@user, @idea), method: 'delete' %>