config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  delete '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  namespace :admin do
    get '/dashboard', to: 'base#dashboard'
    resources :categories
    resources :images
    resources :users
    resources :ideas, only: [:index, :create, :show, :delete]
  end
  resources :users do
    resources :ideas
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name, uniqueness: true, presence: true

  has_many :ideas, dependent: :destroy
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    if Category.create!(category_params)
      flash[:success] = "You have created, #{Category.last.name}!"
      redirect_to admin_category_path(Category.last)
    else
      flash[:failed] = 'Uh...give it a name first?'
      render :new
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def destroy
    category = Category.find(params[:id])
    category.destroy
    flash[:success] = "#{category.name} was successfully deleted!"
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    if Category.create!(category_params)
      flash[:success] = "You have created, #{Category.last.name}!"
      redirect_to category_path(Category.last)
    else
      flash[:failed] = 'Uh...give it a name first?'
      render :new
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def destroy
    category = Category.find(params[:id])
    category.destroy
    flash[:success] = "#{category.name} was successfully deleted!"
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit 'Save Category' %>
<% end %>

app/views/admin/categories/index.html.erb
<h1>All Categories</h1>
<% @categories.each do |c| %>
  <p><%= link_to c.name, admin_category_path(c) %></p></br>
<% end %>

<%= button_to 'Create Category', new_admin_category_path, method: 'get' %>

app/views/admin/categories/show.html.erb
<h1>Name: <%= @category.name %></h1>

<%= button_to 'Delete', admin_category_path(@category), method: 'delete' %>