config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  delete '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  namespace :admin do
    get '/dashboard', to: 'base#dashboard'
    resources :categories
    resources :images
    resources :users
    resources :ideas, only: [:index, :create, :show, :delete]
  end
  resources :users do
    resources :ideas
  end
end

app/models/image.rb
class Image < ApplicationRecord
  validates_presence_of :title, :link, uniqueness: true, presence: true

  has_many :idea_images
  has_many :ideas, through: :idea_images
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::BaseController
  def index
    @images = Image.all
  end

  def new
    @image = Image.new
  end

  def create
    if Image.create!(image_params)
      flash[:success] = "You have created, #{Image.last.title}!"
      redirect_to admin_image_path(Image.last)
    else
      flash[:failed] = 'Uh...give it a name first?'
      render :new
    end
  end

  def show
    @image = Image.find(params[:id])
  end

  def destroy
    image = Image.find(params[:id])
    image.destroy
    flash[:success] = "#{image.title} was successfully deleted!"
    redirect_to admin_images_path
  end

  private

  def image_params
    params.require(:image).permit(:title, :link)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Image.all
  end

  def new
    @image = Image.new
  end

  def create
    if Image.create!(image_params)
      flash[:success] = "You have created, #{Image.last.title}!"
      redirect_to image_path(Image.last)
    else
      flash[:failed] = 'Title and link sailor!'
      render :new
    end
  end

  def show
    @image = Image.find(params[:id])
  end

  private

  def image_params
    params.require(:image).permit(:title, :link)
  end
end

app/views/admin/images/_form.html.erb
<%= form_for [:admin, @image] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :link %>
  <%= f.text_field :link %>
  <%= f.submit 'Save Image' %>
<% end %>

app/views/admin/images/index.html.erb
<h1>All Images</h1>
<div class="all-images">
  <% @images.each do |i| %>
    <div class="idea-image">
      <%= link_to i.title, admin_image_path(i) %>
      <img src="<%= i.link %>">
    </div>
  <% end %>
</div>

<%= button_to 'Create Image', new_admin_image_path, method: 'get' %>

app/views/admin/images/show.html.erb
<h1>Title: <%= @image.title %></h1>
<h2>Image:</h2>
<img src="<%= @image.link %>">

<%= button_to 'Delete', admin_image_path(@image), method: 'delete' %>