config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  delete '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  namespace :admin do
    get '/dashboard', to: 'base#dashboard'
    resources :categories
    resources :images
    resources :users
    resources :ideas, only: [:index, :create, :show, :delete]
  end
  resources :users do
    resources :ideas
  end
end

app/views/layouts/_navbar.html.erb
<nav class='nav-bar'>
  <% if current_admin? %>
    <h2><%= link_to 'Dashboard', admin_dashboard_path %></h2>
    <h2><%= link_to 'Categories', admin_categories_path %></h2>
    <h2><%= link_to 'Images', admin_images_path %></h2>
    <h2><%= link_to 'Users', admin_users_path %></h2>
    <%= button_to 'Logout', logout_path, method: 'delete' %>
  <% elsif current_user %>
    <h2><%= link_to 'Ideas', user_ideas_path(current_user) %></h2>
    <h2><%= link_to 'New Idea', new_user_idea_path(current_user) %></h2>
    <h2><%= link_to 'Profile', user_path(current_user) %></h2>
    <%= button_to 'Logout', logout_path, method: 'delete' %>
  <% else %>
    <div id='nav-login'>
      <%= button_to 'Login', login_path, method: 'get' %>
    </div>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaBox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/navbar' %>
    <section class='flash'>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, sanitize(msg), class: name %>
      <% end %>
    </section>
    <%= yield %>
  </body>
</html>